server:
  port: 9090
  
master:
    user: 
      name: kamlesh
      email: kamlesh.scsit@gmail.com


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health
    password: root
    username: root
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
     ddl-auto: update
    show-sql: true
    
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: kamlesh.javatech@gmail.com
    password: 9424488661@Kamlesh
    properties: 
     mail:
      smtp:
        starttls:
            enable: true 